(() => {
'use strict';
const STORAGE_KEY='somtoday_mod_sticky_notes_v1',BOOL_INDEX=19,ROOT_ID='stm-sticky-notes',MODAL_ID='stm-sticky-modal',SETTING_ID='stm-sticky-notes-setting',HOME_CLASS='stm-sticky-home-host';
const storage=()=>globalThis.browser?.storage?.local||globalThis.chrome?.storage?.local;
async function loadNotes(){try{return(await storage().get(STORAGE_KEY))[STORAGE_KEY]||[]}catch{return[]}}
async function saveNotes(notes){try{await storage().set({[STORAGE_KEY]:notes})}catch{}}
function bools(){return get('bools')||'110001110111101111100000000000'}
function replaceBool(index,value){let b=bools();while(b.length<=index)b+='0';set('bools',b.substring(0,index)+(value?'1':'0')+b.substring(index+1))}
function isEnabled(){const b=get('bools');return !b||b.length<=BOOL_INDEX||b.charAt(BOOL_INDEX)!=='0'}
function esc(value=''){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function isVisible(el){if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'}
function getVisibleHome(){return[...document.querySelectorAll('sl-home')].find(isVisible)||null}
function findLastGradeCard(home){const nodes=[...home.querySelectorAll('h1,h2,h3,h4,h5,p,span,div,a')].filter(el=>isVisible(el)&&/laatste\s+cijfer/i.test((el.textContent||'').trim()));for(const t of nodes){let n=t;while(n&&n!==home){const r=n.getBoundingClientRect();if(r.width>=320&&r.height>=100&&r.height<=260)return n;n=n.parentElement}}return null}
function positionPanel(home,root){const g=findLastGradeCard(home);if(!g)return false;const h=home.getBoundingClientRect(),c=g.getBoundingClientRect(),gap=34,a=window.innerWidth-c.right-gap-18;if(a<240){root.hidden=true;return true}root.hidden=false;root.style.setProperty('--stm-sticky-left',`${Math.round(c.right-h.left+gap)}px`);root.style.setProperty('--stm-sticky-top',`${Math.round(c.top-h.top)}px`);root.style.setProperty('--stm-sticky-width',`${Math.round(Math.min(360,Math.max(250,a)))}px`);return true}
const pencilIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 16.5V20h3.5L18.1 9.4l-3.5-3.5L4 16.5Zm16.7-9.8a1 1 0 0 0 0-1.4l-2-2a1 1 0 0 0-1.4 0l-1.6 1.6 3.5 3.5 1.5-1.7Z"/></svg>',trashIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4h8l1 2h4v2H3V6h4l1-2Zm1 6h2v7H9v-7Zm4 0h2v7h-2v-7Zm4 0h2v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9h2v9h10v-9Z"/></svg>';
async function renderNotes(){const list=document.querySelector('#stm-sticky-list');if(!list)return;const notes=await loadNotes();list.innerHTML=notes.length?notes.map(n=>`<article class="stm-sticky-note" data-id="${esc(n.id)}"><div class="stm-sticky-note-actions"><button class="stm-sticky-edit" type="button" title="Sticky note bewerken" aria-label="Sticky note bewerken">${pencilIcon}</button><button class="stm-sticky-delete" type="button" title="Sticky note verwijderen" aria-label="Sticky note verwijderen">${trashIcon}</button></div><div class="stm-sticky-text">${esc(n.text).replace(/\n/g,'<br>')}</div>${(n.subject||n.date||n.time)?`<div class="stm-sticky-meta">${n.subject?`<span>${esc(n.subject)}</span>`:''}${n.date?`<span>${esc(n.date)}${n.time?` · ${esc(n.time)}`:''}</span>`:(n.time?`<span>${esc(n.time)}</span>`:'')}</div>`:''}</article>`).join(''):'<div class="stm-sticky-empty">Nog geen sticky notes.<br>Maak er eentje voor iets dat je niet wilt vergeten.</div>';list.querySelectorAll('.stm-sticky-delete').forEach(b=>b.onclick=async e=>{e.stopPropagation();const id=b.closest('.stm-sticky-note')?.dataset.id,current=await loadNotes();await saveNotes(current.filter(n=>n.id!==id));renderNotes()});list.querySelectorAll('.stm-sticky-edit').forEach(b=>b.onclick=e=>{e.stopPropagation();openModal(b.closest('.stm-sticky-note')?.dataset.id||null)})}
function closeModal(){const m=document.getElementById(MODAL_ID);if(!m)return;m.classList.add('stm-sticky-modal-closing');setTimeout(()=>m.remove(),160)}
async function openModal(editId=null){if(document.getElementById(MODAL_ID))return;const notes=await loadNotes(),editing=editId?notes.find(n=>n.id===editId):null,m=document.createElement('div');m.id=MODAL_ID;m.className='stm-sticky-modal-backdrop';m.innerHTML=`<section class="stm-sticky-modal" role="dialog" aria-modal="true"><div class="stm-sticky-modal-header"><div><span class="stm-sticky-kicker">Somtoday Mod</span><h2>${editing?'Sticky note bewerken':'Sticky note maken'}</h2><p>${editing?'Pas je notitie aan.':'Zet iets belangrijks direct op je startpagina.'}</p></div><button class="stm-sticky-close" type="button">×</button></div><label class="stm-sticky-field"><span>Notitie</span><textarea id="stm-sticky-input" maxlength="600" rows="5">${editing?esc(editing.text):''}</textarea></label><div class="stm-sticky-fields-row"><label class="stm-sticky-field"><span>Datum <small>optioneel</small></span><input id="stm-sticky-date" type="date" value="${editing?esc(editing.date||''):''}"></label><label class="stm-sticky-field"><span>Tijd <small>optioneel</small></span><input id="stm-sticky-time" type="time" value="${editing?esc(editing.time||''):''}"></label></div><label class="stm-sticky-field"><span>Vak <small>optioneel</small></span><input id="stm-sticky-subject" type="text" maxlength="60" value="${editing?esc(editing.subject||''):''}"></label><div class="stm-sticky-modal-actions"><button class="stm-sticky-cancel" type="button">Annuleren</button><button class="stm-sticky-create" type="button">${editing?'Wijzigingen opslaan':'Sticky note maken'}</button></div></section>`;document.body.appendChild(m);requestAnimationFrame(()=>m.classList.add('stm-sticky-modal-visible'));m.querySelector('.stm-sticky-close').onclick=closeModal;m.querySelector('.stm-sticky-cancel').onclick=closeModal;m.onclick=e=>{if(e.target===m)closeModal()};m.querySelector('.stm-sticky-create').onclick=async()=>{const text=m.querySelector('#stm-sticky-input').value.trim();if(!text){m.querySelector('#stm-sticky-input').focus();return}const latest=await loadNotes(),payload={id:editing?.id||`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,text,date:m.querySelector('#stm-sticky-date').value,time:m.querySelector('#stm-sticky-time').value,subject:m.querySelector('#stm-sticky-subject').value.trim()};if(editing){const i=latest.findIndex(n=>n.id===editing.id);if(i!==-1)latest[i]=payload}else latest.unshift(payload);await saveNotes(latest);closeModal();renderNotes()};setTimeout(()=>m.querySelector('#stm-sticky-input')?.focus(),80)}
function createPanel(){const r=document.createElement('section');r.id=ROOT_ID;r.className='stm-sticky-panel';r.innerHTML='<div class="stm-sticky-panel-header"><div><span class="stm-sticky-kicker">Somtoday Mod</span><h3>Sticky Notes</h3></div><span class="stm-sticky-pin">●</span></div><button type="button" class="stm-sticky-add">+ <span>Sticky Note Maken</span></button><div id="stm-sticky-list" class="stm-sticky-list"></div>';r.querySelector('.stm-sticky-add').onclick=()=>openModal();return r}
function cleanup(){document.getElementById(ROOT_ID)?.remove();document.querySelectorAll(`.${HOME_CLASS}`).forEach(el=>el.classList.remove(HOME_CLASS))}
function injectSetting(){const cat=document.getElementById('category-extra');if(!cat||document.getElementById(SETTING_ID))return;const tasks=cat.querySelector('#bools16'),tasksRow=tasks?.closest('div');if(!tasksRow)return;const row=tasksRow.cloneNode(true);row.id=SETTING_ID;const title=row.querySelector('h3'),cb=row.querySelector('input[type="checkbox"]'),label=row.querySelector('label.switch');if(!cb||!label)return;if(title)title.textContent='Sticky Notes op startpagina';cb.id='bools19';cb.title='Sticky Notes op startpagina';cb.className='mod-custom-setting';cb.removeAttribute('oninput');label.setAttribute('for','bools19');cb.checked=isEnabled();cb.addEventListener('change',()=>cb.classList.add('mod-modified'));label.addEventListener('click',e=>{if(e.target===cb)return;e.preventDefault();cb.checked=!cb.checked;cb.dispatchEvent(new Event('change',{bubbles:true}))});tasksRow.insertAdjacentElement('afterend',row)}
function savePendingSetting(){const cb=document.getElementById('bools19');if(!cb)return;replaceBool(BOOL_INDEX,cb.checked);cb.classList.remove('mod-modified')}
document.addEventListener('click',e=>{const b=e.target.closest?.('button,hmy-button');if(!b)return;const text=(b.textContent||'').trim();if(b.id==='save'||/instellingen\s+opslaan/i.test(text)){savePendingSetting();setTimeout(mount,60)}},true);
function mount(){injectSetting();if(!isEnabled()){cleanup();return}const home=getVisibleHome();if(!home){cleanup();return}document.querySelectorAll(`.${HOME_CLASS}`).forEach(el=>{if(el!==home)el.classList.remove(HOME_CLASS)});home.classList.add(HOME_CLASS);const existing=document.getElementById(ROOT_ID),root=existing||createPanel();if(root.parentElement!==home)home.appendChild(root);if(!positionPanel(home,root)){root.remove();return}if(!existing)renderNotes()}
let timer;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,100)});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',mount);window.addEventListener('popstate',mount);window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(mount,80)});setInterval(mount,900);setTimeout(mount,200);
})();

(() => {
'use strict';
const STORAGE_KEY='somtoday_mod_apps_v1',BOOL_INDEX=20,SETTING_ID='stm-apps-setting',PAGE_ID='stm-apps-page',MODAL_ID='stm-apps-modal';
const storage=()=>globalThis.browser?.storage?.local||globalThis.chrome?.storage?.local;
let appsOpen=false,previousTopTitle='';
const gridIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h6v6h-6v-6Z"/></svg>',pencilIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 16.5V20h3.5L18.1 9.4l-3.5-3.5L4 16.5Zm16.7-9.8a1 1 0 0 0 0-1.4l-2-2a1 1 0 0 0-1.4 0l-1.6 1.6 3.5 3.5 1.5-1.7Z"/></svg>',trashIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4h8l1 2h4v2H3V6h4l1-2Zm1 6h2v7H9v-7Zm4 0h2v7H9v-7Zm4 0h2v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-9h2v9h10v-9Z"/></svg>';
function bools(){return get('bools')||'110001110111101111100000000000'}
function replaceBool(index,value){let b=bools();while(b.length<=index)b+='0';set('bools',b.substring(0,index)+(value?'1':'0')+b.substring(index+1))}
function isEnabled(){const b=get('bools');return !b||b.length<=BOOL_INDEX||b.charAt(BOOL_INDEX)!=='0'}
function esc(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
async function loadApps(){try{return(await storage().get(STORAGE_KEY))[STORAGE_KEY]||[]}catch{return[]}}
async function saveApps(apps){try{await storage().set({[STORAGE_KEY]:apps})}catch{}}
function normalizeUrl(value){let v=(value||'').trim();if(!v)return'';if(!/^https?:\/\//i.test(v))v='https://'+v;try{const u=new URL(v);return/^https?:$/.test(u.protocol)?u.href:''}catch{return''}}
function injectSetting(){const cat=document.getElementById('category-extra');if(!cat||document.getElementById(SETTING_ID))return;const base=document.getElementById('stm-sticky-notes-setting')||cat.querySelector('#bools16')?.closest('div');if(!base)return;const row=(cat.querySelector('#bools16')?.closest('div')||base).cloneNode(true);row.id=SETTING_ID;const title=row.querySelector('h3'),cb=row.querySelector('input[type="checkbox"]'),label=row.querySelector('label.switch');if(!cb||!label)return;if(title)title.textContent='Apps-pagina';cb.id='bools20';cb.title='Apps-pagina';cb.className='mod-custom-setting';cb.removeAttribute('oninput');label.setAttribute('for','bools20');cb.checked=isEnabled();cb.addEventListener('change',()=>cb.classList.add('mod-modified'));label.addEventListener('click',e=>{if(e.target===cb)return;e.preventDefault();cb.checked=!cb.checked;cb.dispatchEvent(new Event('change',{bubbles:true}))});base.insertAdjacentElement('afterend',row)}
function savePendingSetting(){const cb=document.getElementById('bools20');if(!cb)return;replaceBool(BOOL_INDEX,cb.checked);cb.classList.remove('mod-modified')}
function navCandidates(){return[...document.querySelectorAll('sl-tab-bar')].filter(b=>b.querySelector('sl-tab-item'))}
function makeNavItem(template){const item=template.cloneNode(true);item.classList.remove('active');item.classList.add('stm-apps-nav-item');item.removeAttribute('href');item.querySelectorAll('hmy-notification-counter').forEach(e=>e.remove());const span=item.querySelector('span');if(span)span.textContent='Apps';const icon=item.querySelector('i');if(icon)icon.innerHTML=gridIcon;else{const target=item.querySelector('.item')||item;target.insertAdjacentHTML('afterbegin',`<i class="stm-apps-nav-icon">${gridIcon}</i>`)}item.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openPage()});return item}
function injectNav(){if(!isEnabled())return;for(const bar of navCandidates()){if(bar.querySelector('.stm-apps-nav-item'))continue;const items=[...bar.querySelectorAll(':scope > sl-tab-item')];const template=items[1]||items[0];if(template)bar.appendChild(makeNavItem(template))}}
function removeNav(){document.querySelectorAll('.stm-apps-nav-item').forEach(e=>e.remove())}
function setActive(active){document.querySelectorAll('.stm-apps-nav-item').forEach(e=>e.classList.toggle('active',active));if(active)document.querySelectorAll('sl-tab-item:not(.stm-apps-nav-item).active').forEach(e=>e.classList.remove('active'))}
function updateTopTitle(open){const el=document.getElementById('mod-top-menu-title');if(!el)return;if(open){if(!previousTopTitle)previousTopTitle=el.textContent||'';el.textContent='Apps'}else if(previousTopTitle){el.textContent=previousTopTitle;previousTopTitle=''}}
function closePage(){appsOpen=false;document.getElementById(PAGE_ID)?.remove();document.getElementById(MODAL_ID)?.remove();setActive(false);updateTopTitle(false)}
async function openPage(){if(!isEnabled())return;appsOpen=true;let page=document.getElementById(PAGE_ID);if(!page){page=document.createElement('section');page.id=PAGE_ID;page.className=`stm-apps-page stm-apps-layout-${get('layout')||1}`;page.innerHTML='<div class="stm-apps-shell"><div class="stm-apps-heading"><div><span class="stm-apps-kicker">Somtoday Mod</span><h1>Apps</h1><p>Voeg je eigen snelle links toe.</p></div></div><div id="stm-apps-grid" class="stm-apps-grid"></div></div>';document.body.appendChild(page)}setActive(true);updateTopTitle(true);await renderApps()}
async function renderApps(){const grid=document.getElementById('stm-apps-grid');if(!grid)return;const apps=await loadApps();grid.innerHTML=`<button type="button" class="stm-apps-add"><span class="stm-apps-plus">+</span><span>App toevoegen</span></button>`+apps.map(app=>{const initial=esc((app.name||'?').trim().charAt(0).toUpperCase()||'?'),icon=app.icon?`<img src="${esc(app.icon)}" alt="">`:'';return`<article class="stm-app-card" data-id="${esc(app.id)}" tabindex="0"><div class="stm-app-actions"><button class="stm-app-edit" title="App bewerken">${pencilIcon}</button><button class="stm-app-delete" title="App verwijderen">${trashIcon}</button></div><div class="stm-app-icon">${icon}<span>${initial}</span></div><div class="stm-app-name">${esc(app.name)}</div><div class="stm-app-url">${esc(app.url)}</div></article>`}).join('');grid.querySelector('.stm-apps-add').onclick=()=>openModal();grid.querySelectorAll('.stm-app-card').forEach(card=>{const open=()=>{const app=apps.find(a=>a.id===card.dataset.id);if(app)window.open(app.url,'_blank','noopener,noreferrer')};card.addEventListener('click',e=>{if(!e.target.closest('.stm-app-actions'))open()});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('.stm-app-actions')){e.preventDefault();open()}});const img=card.querySelector('img');if(img)img.addEventListener('error',()=>img.remove());card.querySelector('.stm-app-edit').onclick=e=>{e.stopPropagation();openModal(card.dataset.id)};card.querySelector('.stm-app-delete').onclick=async e=>{e.stopPropagation();await saveApps(apps.filter(a=>a.id!==card.dataset.id));renderApps()}})}
function closeModal(){document.getElementById(MODAL_ID)?.remove()}
async function openModal(editId=null){if(document.getElementById(MODAL_ID))return;const apps=await loadApps(),editing=editId?apps.find(a=>a.id===editId):null,m=document.createElement('div');m.id=MODAL_ID;m.className='stm-apps-modal-backdrop';m.innerHTML=`<section class="stm-apps-modal" role="dialog" aria-modal="true"><div class="stm-apps-modal-header"><div><span class="stm-apps-kicker">Somtoday Mod</span><h2>${editing?'App bewerken':'App toevoegen'}</h2></div><button class="stm-apps-close" type="button">×</button></div><label class="stm-apps-field"><span>App naam</span><input id="stm-app-name" maxlength="50" value="${editing?esc(editing.name):''}" placeholder="Bijv. Teams"></label><label class="stm-apps-field"><span>Link URL</span><input id="stm-app-url" maxlength="1000" value="${editing?esc(editing.url):''}" placeholder="https://..."></label><label class="stm-apps-field"><span>Icon URL <small>optioneel</small></span><input id="stm-app-icon" maxlength="1000" value="${editing?esc(editing.icon||''):''}" placeholder="https://..."></label><p class="stm-apps-hint">Geen icon? Dan gebruiken we automatisch de eerste letter van de appnaam.</p><div class="stm-apps-modal-actions"><button class="stm-apps-cancel" type="button">Annuleren</button><button class="stm-apps-save" type="button">${editing?'Wijzigingen opslaan':'App toevoegen'}</button></div></section>`;document.body.appendChild(m);m.querySelector('.stm-apps-close').onclick=closeModal;m.querySelector('.stm-apps-cancel').onclick=closeModal;m.onclick=e=>{if(e.target===m)closeModal()};m.querySelector('.stm-apps-save').onclick=async()=>{const name=m.querySelector('#stm-app-name').value.trim(),url=normalizeUrl(m.querySelector('#stm-app-url').value),rawIcon=m.querySelector('#stm-app-icon').value.trim(),icon=rawIcon?normalizeUrl(rawIcon):'';if(!name){m.querySelector('#stm-app-name').focus();return}if(!url){m.querySelector('#stm-app-url').focus();return}if(rawIcon&&!icon){m.querySelector('#stm-app-icon').focus();return}const latest=await loadApps(),payload={id:editing?.id||`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name,url,icon};if(editing){const i=latest.findIndex(a=>a.id===editing.id);if(i!==-1)latest[i]=payload}else latest.push(payload);await saveApps(latest);closeModal();renderApps()};setTimeout(()=>m.querySelector('#stm-app-name')?.focus(),50)}
document.addEventListener('click',e=>{const save=e.target.closest?.('button,hmy-button');if(save){const text=(save.textContent||'').trim();if(save.id==='save'||/instellingen\s+opslaan/i.test(text)){savePendingSetting();setTimeout(sync,80)}}const tab=e.target.closest?.('sl-tab-item');if(tab&&!tab.classList.contains('stm-apps-nav-item')&&appsOpen)setTimeout(closePage,0)},true);
function sync(){injectSetting();if(!isEnabled()){removeNav();closePage();return}injectNav();if(appsOpen&&!document.getElementById(PAGE_ID))openPage()}
let timer;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(sync,120)});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('resize',sync);window.addEventListener('popstate',()=>{if(appsOpen)closePage()});setInterval(sync,1000);setTimeout(sync,250);
})();