(() => {
'use strict';
const STORAGE_KEY='somtoday_mod_apps_v1',PAGE_ID='stm-apps-page',STYLE_ID='stm-apps-enhancements-style';
const storage=()=>globalThis.browser?.storage?.local||globalThis.chrome?.storage?.local;
const pinIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 3l7 7-2 2-2-2-4 4v3l-2 2-2-5-5-2 2-2h3l4-4-2-2 3-1Z"/><path d="M8 16l-5 5"/></svg>';
let query='',enhancing=false;
async function loadApps(){try{return(await storage().get(STORAGE_KEY))[STORAGE_KEY]||[]}catch{return[]}}
async function saveApps(apps){try{await storage().set({[STORAGE_KEY]:apps})}catch{}}
function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.stm-apps-tools{display:flex;align-items:center;gap:10px;margin:0 0 22px}.stm-apps-search-wrap{position:relative;width:min(440px,100%)}.stm-apps-search-icon{position:absolute;left:13px;top:50%;transform:translateY(-50%);width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:2;color:var(--text-moderate,var(--fg-neutral-moderate));pointer-events:none}.stm-apps-search{box-sizing:border-box;width:100%;height:43px;padding:0 40px;border:var(--thinnest-solid-neutral-normal);border-radius:11px;background:var(--bg-elevated-weakest,var(--bg-neutral-none));color:var(--text-strong);font:inherit;font-size:13px;outline:none;transition:border-color .15s,box-shadow .15s}.stm-apps-search:focus{border-color:var(--action-primary-normal,#0067c2);box-shadow:0 0 0 3px color-mix(in srgb,var(--action-primary-normal,#0067c2) 14%,transparent)}.stm-apps-search-clear{position:absolute;right:8px;top:7px;width:29px;height:29px;border:0;border-radius:7px;background:transparent;color:var(--text-moderate);font-size:18px;cursor:pointer}.stm-apps-search-clear:hover{background:var(--bg-primary-weak)}.stm-apps-search-empty{grid-column:1/-1;padding:42px 16px;text-align:center;color:var(--text-moderate,var(--fg-neutral-moderate));font-size:13px}.stm-app-pin{position:absolute;top:8px;left:8px;z-index:5;display:flex;align-items:center;justify-content:center;width:30px;height:30px;padding:0;border:var(--thinnest-solid-neutral-normal);border-radius:8px;background:var(--bg-neutral-none);color:var(--text-moderate,var(--fg-neutral-moderate));cursor:pointer;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .12s,color .12s,background .12s}.stm-app-card:hover .stm-app-pin,.stm-app-card:focus-within .stm-app-pin,.stm-app-card.stm-app-pinned .stm-app-pin{opacity:1;visibility:visible;pointer-events:auto}.stm-app-pin:hover{color:var(--action-primary-normal,#0067c2);background:var(--bg-primary-weak)}.stm-app-pin svg{width:16px;height:16px;fill:currentColor}.stm-app-card.stm-app-pinned .stm-app-pin{color:var(--action-primary-normal,#0067c2);background:color-mix(in srgb,var(--bg-primary-weak) 70%,var(--bg-neutral-none))}.stm-app-card.stm-app-pinned{border-color:color-mix(in srgb,var(--action-primary-normal,#0067c2) 30%,transparent)}.stm-apps-pin-badge{position:absolute;right:9px;bottom:9px;display:flex;align-items:center;justify-content:center;width:22px;height:22px;border-radius:7px;background:var(--action-primary-normal,#0067c2);color:#fff;box-shadow:0 2px 7px rgba(0,0,0,.14);pointer-events:none}.stm-apps-pin-badge svg{width:12px;height:12px;fill:currentColor}.stm-app-card .stm-app-actions{right:8px;z-index:5}.stm-app-card.stm-app-filter-hidden{display:none!important}@media(max-width:620px){.stm-apps-tools{margin-bottom:16px}.stm-apps-search-wrap{width:100%}.stm-app-pin{opacity:1;visibility:visible;pointer-events:auto}}
`;document.head.appendChild(s)}
function ensureSearch(){const page=document.getElementById(PAGE_ID),shell=page?.querySelector('.stm-apps-shell'),grid=page?.querySelector('#stm-apps-grid');if(!shell||!grid)return;let tools=page.querySelector('.stm-apps-tools');if(!tools){tools=document.createElement('div');tools.className='stm-apps-tools';tools.innerHTML=`<div class="stm-apps-search-wrap"><svg class="stm-apps-search-icon" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input class="stm-apps-search" type="search" maxlength="80" autocomplete="off" placeholder="Zoek apps op naam…" aria-label="Apps zoeken"><button class="stm-apps-search-clear" type="button" title="Zoekopdracht wissen" aria-label="Zoekopdracht wissen">×</button></div>`;grid.before(tools);const input=tools.querySelector('.stm-apps-search');input.value=query;input.addEventListener('input',()=>{query=input.value;applyFilter()});tools.querySelector('.stm-apps-search-clear').onclick=()=>{query='';input.value='';input.focus();applyFilter()}}}
function applyFilter(){const page=document.getElementById(PAGE_ID);if(!page)return;const q=query.trim().toLocaleLowerCase('nl-NL');let shown=0;page.querySelectorAll('.stm-app-card').forEach(card=>{const name=(card.querySelector('.stm-app-name')?.textContent||'').toLocaleLowerCase('nl-NL'),hide=!!q&&!name.includes(q);card.classList.toggle('stm-app-filter-hidden',hide);if(!hide)shown++});let empty=page.querySelector('.stm-apps-search-empty');if(q&&shown===0){if(!empty){empty=document.createElement('div');empty.className='stm-apps-search-empty';page.querySelector('#stm-apps-grid')?.appendChild(empty)}empty.textContent=`Geen apps gevonden voor “${query.trim()}”.`}else empty?.remove();const add=page.querySelector('.stm-apps-add');if(add)add.style.display=q?'none':''}
async function togglePin(id){const apps=await loadApps(),index=apps.findIndex(a=>String(a.id)===String(id));if(index<0)return;apps[index]={...apps[index],pinned:!apps[index].pinned};await saveApps(apps);await enhance()}
async function enhanceCards(){const page=document.getElementById(PAGE_ID);if(!page)return;const apps=await loadApps(),order=new Map(apps.map((a,i)=>[String(a.id),i]));const sorted=[...apps].sort((a,b)=>(Number(!!b.pinned)-Number(!!a.pinned))||((order.get(String(a.id))??0)-(order.get(String(b.id))??0)));const grid=page.querySelector('#stm-apps-grid');if(!grid)return;
for(const app of sorted){const card=grid.querySelector(`.stm-app-card[data-id="${CSS.escape(String(app.id))}"]`);if(!card)continue;card.classList.toggle('stm-app-pinned',!!app.pinned);let pin=card.querySelector('.stm-app-pin');if(!pin){pin=document.createElement('button');pin.type='button';pin.className='stm-app-pin';pin.innerHTML=pinIcon;pin.addEventListener('mousedown',e=>e.stopPropagation());pin.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();togglePin(card.dataset.id)});card.appendChild(pin)}pin.title=app.pinned?'Losmaken':'Vastpinnen';pin.setAttribute('aria-label',pin.title);pin.setAttribute('aria-pressed',app.pinned?'true':'false');let badge=card.querySelector('.stm-apps-pin-badge');if(app.pinned&&!badge){badge=document.createElement('span');badge.className='stm-apps-pin-badge';badge.title='Vastgepind';badge.innerHTML=pinIcon;card.appendChild(badge)}else if(!app.pinned)badge?.remove()}
const desired=sorted.map(a=>String(a.id));const current=[...grid.querySelectorAll('.stm-app-card')].map(c=>String(c.dataset.id));if(desired.some((id,i)=>id!==current[i])){for(const id of desired){const card=grid.querySelector(`.stm-app-card[data-id="${CSS.escape(id)}"]`);if(card)grid.appendChild(card)}}applyFilter()}
async function enhance(){if(enhancing)return;enhancing=true;try{ensureStyle();ensureSearch();await enhanceCards()}finally{enhancing=false}}
let queued=false;function schedule(){if(queued||enhancing)return;queued=true;setTimeout(()=>{queued=false;enhance()},80)}
new MutationObserver(mutations=>{if(enhancing)return;const relevant=mutations.some(m=>[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1&&(n.id===PAGE_ID||n.querySelector?.(`#${PAGE_ID}`)||n.closest?.(`#${PAGE_ID}`))));if(relevant)schedule()}).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('stm-apps-state-change',schedule);setInterval(()=>{if(document.getElementById(PAGE_ID))schedule()},1200);setTimeout(schedule,300);
})();